# Lati. & Longi. of Toronto Neighborhoods

### using the csv file

## Setup and DataFrames from pervious Notebook

In [3]:
!conda install -c anaconda beautifulsoup4 --yes
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np

#getting relevant page content
wiki_page = requests.get("https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M")
soup = BeautifulSoup(wiki_page.content, 'html.parser')

#creating DF
table = soup.find('tbody')
rows = table.select('tr')
row = [r.get_text() for r in rows]
df = pd.DataFrame(row)

#cleanling and organizing DF
df1 = df[0].str.split('\n', expand=True)
df1.rename(columns=df1.iloc[0], inplace=True)
df1.drop(df1.index[0], inplace=True)

# new df with no NAN Boroughs
df2 = df1[df1.Borough != 'Not assigned']

#new df with combined Neighborhoods
df3 = df2.groupby(['Postcode', 'Borough'], sort = False).agg(','.join)
df3.reset_index(inplace=True)

df3.replace("Not assigned", "Queen's Park", inplace=True)
df3.head()

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.7.12

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/jupyterlab/conda/envs/python

  added / updated specs:
    - beautifulsoup4


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numpy-base-1.15.4          |   py36h81de0dd_0         4.2 MB  anaconda
    numpy-1.15.4               |   py36h1d66e8a_0          35 KB  anaconda
    beautifulsoup4-4.8.1       |           py36_0         153 KB  anaconda
    openssl-1.1.1              |       h7b6447c_0         5.0 MB  anaconda
    soupsieve-1.9.5            |           py36_0          61 KB  anaconda
    mkl_fft-1.0.6              |   py36h7dd41cf_0         150 KB  anaconda
    certifi-2019.11.28         |           py36_0         156 KB  anaconda
    blas-1.0                   |              mkl           6 KB  anaconda
    scipy-1.1.0                |   py36hfa4b5c9_1        18.0 MB  anaconda
    mkl_random-1.0.1           |   py36h4414c95_1         373 KB  anaconda
    scikit-learn-0.20.1        |   py36h4989274_0         5.7 MB  anaconda
    ------------------------------------------------------------
                                           Total:        33.8 MB

The following NEW packages will be INSTALLED:

    soupsieve:      1.9.5-py36_0                           anaconda

The following packages will be UPDATED:

    beautifulsoup4: 4.6.3-py37_0                                       --> 4.8.1-py36_0          anaconda
    certifi:        2019.9.11-py36_0                       conda-forge --> 2019.11.28-py36_0     anaconda
    mkl_fft:        1.0.4-py37h4414c95_1                               --> 1.0.6-py36h7dd41cf_0  anaconda
    mkl_random:     1.0.1-py37h4414c95_1                               --> 1.0.1-py36h4414c95_1  anaconda
    numpy-base:     1.15.1-py37h81de0dd_0                              --> 1.15.4-py36h81de0dd_0 anaconda
    openssl:        1.1.1d-h516909a_0                      conda-forge --> 1.1.1-h7b6447c_0      anaconda

The following packages will be DOWNGRADED:

    blas:           1.1-openblas                           conda-forge --> 1.0-mkl               anaconda
    numpy:          1.16.2-py36_blas_openblash1522bff_0    conda-forge [blas_openblas] --> 1.15.4-py36h1d66e8a_0 anaconda
    scikit-learn:   0.20.1-py36_blas_openblashebff5e3_1200 conda-forge [blas_openblas] --> 0.20.1-py36h4989274_0 anaconda
    scipy:          1.2.1-py36_blas_openblash1522bff_0     conda-forge [blas_openblas] --> 1.1.0-py36hfa4b5c9_1  anaconda


Downloading and Extracting Packages
numpy-base-1.15.4    | 4.2 MB    | ##################################### | 100%
numpy-1.15.4         | 35 KB     | ##################################### | 100%
beautifulsoup4-4.8.1 | 153 KB    | ##################################### | 100%
openssl-1.1.1        | 5.0 MB    | ##################################### | 100%
soupsieve-1.9.5      | 61 KB     | ##################################### | 100%
mkl_fft-1.0.6        | 150 KB    | ##################################### | 100%
certifi-2019.11.28   | 156 KB    | ##################################### | 100%
blas-1.0             | 6 KB      | ##################################### | 100%
scipy-1.1.0          | 18.0 MB   | ##################################### | 100%
mkl_random-1.0.1     | 373 KB    | ##################################### | 100%
scikit-learn-0.20.1  | 5.7 MB    | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

  Postcode           Borough                    Neighbourhood
0      M3A        North York                        Parkwoods
1      M4A        North York                 Victoria Village
2      M5A  Downtown Toronto                     Harbourfront
3      M6A        North York  Lawrence Heights,Lawrence Manor
4      M7A      Queen's Park                     Queen's Park

### Getting CSV File & renaming Column

In [11]:
url = "http://cocl.us/Geospatial_data"
df_LL = pd.read_csv(url)
df_LL.rename(columns={'Postal Code': 'Postcode'}, inplace=True)
df_LL.head()

  Postcode   Latitude  Longitude
0      M1B  43.806686 -79.194353
1      M1C  43.784535 -79.160497
2      M1E  43.763573 -79.188711
3      M1G  43.770992 -79.216917
4      M1H  43.773136 -79.239476

### Merging both DFs to get final DF

In [12]:
df_final = pd.merge(df3, df_LL, on='Postcode')
df_final.head()

,Postcode,Borough,Neighbourhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.753259,-79.329656
1,M4A,North York,Victoria Village,43.725882,-79.315572
2,M5A,Downtown Toronto,Harbourfront,43.654260,-79.360636
3,M6A,North York,"Lawrence Heights,Lawrence Manor",43.718518,-79.464763
4,M7A,Queen's Park,Queen's Park,43.662301,-79.389494